name: Continuous Integration
on: [pull_request, push]
jobs:
  build:
    runs-on: fedora-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - name: Build
      run: |
        npm ci
        npm run build
    - name: Upload Coverage
      uses: Atrox/codecov-action@v0.1.2
      env:
        CODECOV_TOKEN: 978d2775-8f96-48dc-9dfd-3d191d642e96
